<h1 class="text-center mb-5">Frequently Asked Questions</h1>
<div id="accordionExample" class="accordion">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h2 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Can I bring my pet flamingo to the party?
                </button>
            </h2>
        </div>
        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                Yes! We love flamingos. Please bring your flamingo to the party.
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-header" id="headingTwo">
        <h2 class="mb-0">
            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                Where the fuck is the beer?
            </button>
        </h2>
    </div>
    <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                If you were invited by one of the hosts, you should have received beer already. If we don't know you, you're not getting any beer. We're not your mothers. However if you identify as a hot person - please check our <a href="/special_offer">special offer! </a>
            </div>

        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingThree">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                    Wifi password?
                </button>
            </h2>
        </div>
        <div id="collapseThree" class="collapse show" aria-labelledby="headingThree" data-parent="#accordionExample">
            <div class="card-body">
                Fuck off.
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingFour">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                    Can I bring a llama as my plus one?
                </button>
            </h2>
        </div>
        <div id="collapseFour" class="collapse show" aria-labelledby="headingFour" data-parent="#accordionExample">
            <div class="card-body">
                Yes. Llamas are welcome at the party. Just make sure you bring enough drugs and drinks for the both of you. We are not sharing with you!
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingFive">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                    Is there a dress code for the party?
                </button>
            </h2>
        </div>
        <div id="collapseFive" class="collapse show" aria-labelledby="headingFive" data-parent="#accordionExample">
            <div class="card-body">
                Yes, the dress code is hot/sexy.
            </div>
        </div>
    </div>