      <!-- add a picture of the WG6 -->
      <div class="text-center">
        <img
          src="images/wg6.jpg"
          alt="WG6"
          class="img-fluid rounded"
          width="500"
        />
      <h1 class="text-center mb-1">
        Welcome to <br />
        WG6 2023 Drinking Championship
      </h1>
      <!-- add a small button allowing user to navigate to german version -->
      <div class="text-center">
        <a href="website-wg6/home_de.html" class="btn btn-xs custom-button my-3">
          German Version
        </a>
      </div>
      <p class="lead">
        We're excited to announce that this year's tournament will be held at
        <strong>01:30</strong> at our apartment. Make sure to be there on time
        and bring your best game face.
      </p>
      <h2 class="mt-5 mb-3">Tournament Details</h2>
      <ol>
        <li>
          <p>
            <strong>Handicap Round - Mega Rage Cage</strong><br />
            We'll use 5, 6, or 7 balls depending on how many people sign up.
          </p>
        </li>
        <li>
          <p>
            <strong>Random Teams Allocation Beer Pong Round</strong><br />
            We'll put you in teams with random people and make you play against
            each other until only 25% qualify for the next round.
          </p>
          <p>
            For time-constraint reasons we are going to have to use a reduced
            amount of cups :(
          </p>
          <p class="text-center small text-muted">
            *Note: If the game takes too long, the organizers reserve the right
            to settle it with a beer tornado. May the best man or woman win!
          </p>
        </li>
        <li>
          <p>
            <strong>Flunky Ball Free for All</strong><br />
            The top 25% will play a round of flunky ball outside in the
            Coutryad. The first three to win will be declared the winners and
            will receive prizes, with the first person being declared the King
            of WG6 Tournament 2023 &#128081; The last three remaining in Flunky
            Ball will have to complete a punishment!
          </p>
          <p class="announcement">
            Go to the poll and vote for the punishment you want to see them do!
            <a href="/punishment"></a>
          </p>
        </li>
      </ol>
      <br />
      <p class="mt-3 text-center">
        <strong
          >Do you think you have what it takes? Click the link below!</strong
        >
      </p>
      <!-- add a registration button with a lot of party theme -->
      <div class="text-center">
        <a href="registration.html" class="btn btn-lg custom-button">
          Prove you are worthy.
          <br />
          Claim the crown. <br />
          Register now.
        </a>
      </div>
