<!-- Navbar -->
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">WG6</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="index.phtml">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="faq.phtml">FAQ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="punishment.phtml">Punishment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="registration.phtml">Registration</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="residents.phtml">Residents</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="special_offer.phtml">Special Offer</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
