<form action="results.html">
    <div class="form-group">
        <label for="punishment-1">Naked Mile - in Brücke</label>
        <input type="radio" name="punishment" id="punishment-1" value="option-1">
    </div>
    <div class="form-group">
        <label for="punishment-2">Naked Mile - Uni Campus</label>
        <input type="radio" name="punishment" id="punishment-2" value="option-2">
    </div>
    <div class="form-group">
        <label for="punishment-3">Have to wear the most ridiculous outfit for the rest of the day <br> You get to pick the outfits!</label>
        <input type="radio" name="punishment" id="punishment-3" value="option-3">
    </div>
    <div class="form-group">
        <label for="punishment-4">Body shots from people chosen by the top 3</label>
        <input type="radio" name="punishment" id="punishment-4" value="option-4">
    </div>
    <div class="form-group">
        <label for="punishment-5">A kiss from Maher</label>
        <input type="radio" name="punishment" id="punishment-5" value="option-5">
    </div>
    <button type="submit" class="custom-button my-3 btn btn-primary btn-lg">Submit</button>
</form>