<h1 class="text-center mb-5">Meet the Residents</h1>
      <div class="row">
        <div class="col-md-4 mb-3">
          <img
            src="images/Maher1.jpg"
            class="img-fluid rounded-circle"
            alt="Person 1"
          />
          <img
            src="images/Maher2.jpg"
            class="img-fluid rounded-circle"
            alt="Person 1"
          />
          <img
            src="images/Maher3.jpg"
            class="img-fluid rounded-circle"
            alt="Person 1"
          />
          <h2>Maher</h2>
          <p>
            Maher is the idiot who created this website. Why? I had too much
            free time this morning, I am also single, so this is as
            fun as it gets for me....
          </p>
        </div>
        <div class="col-md-4 mb-3">
          <img
            src="images/Filip1.jpg"
            class="img-fluid rounded-circle"
            alt="Filip"
          />
          <img
            src="images/Filip2.jpg"
            class="img-fluid rounded-circle"
            alt="Filip"
          />
          <img
            src="images/Filip3.jpg"
            class="img-fluid rounded-circle"
            alt="Filip"
          />
          <h2>Filip</h2>
          <p>
            Filip is the person responsible for making sure this WG is always
            stocked with beer. He likes metal, technology and he has only black
            clothes. He also loves his hair way too much. Also the person with
            the highest alcohol tolerance in the WG - but somehow he is always
            the drunkest person at every party.
          </p>
        </div>
        <div class="col-md-4 mb-3">
          <img
            src="images/Viktoria1.jpg"
            class="img-fluid rounded-circle"
            alt="Viktoria"
          />
          <img
            src="images/Viktoria2.jpg"
            class="img-fluid rounded-circle"
            alt="Viktoria"
          />
          <img
            src="images/Viktoria3.jpg"
            class="img-fluid rounded-circle"
            alt="Viktoria"
          />
          <h2>Viktoria</h2>
          <p>
            Viktoria is the newest member of our household. She has already went
            through 17 mental crises and 4 breakdowns in the WG. She is small
            but surprisingly powerful. She may not seem like she can do a lot of
            damage, but she will destroy you emotionally if you force her. Treat
            with caution
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 mb-3">
          <img
            src="images/Ahmed1.jpg"
            class="img-fluid rounded-circle"
            alt="Ahmed"
          />
          <img
            src="images/Ahmed2.jpg"
            class="img-fluid rounded-circle"
            alt="Ahmed"
          />
          <img
            src="images/Ahmed3.jpg"
            class="img-fluid rounded-circle"
            alt="Ahmed"
          />
          <h2>Ahmed</h2>
          <p>
            Ahmed is the person responsible for making sure this WG is
            maintained and doesn't break down too often. Easily the best tutor
            in the Brücke "We asked people". He is the life of the party and may
            be found at later levels of drunkness dancing actually pretty good.
          </p>
        </div>
        <div class="col-md-4 mb-3">
          <img
            src="images/Azam1.jpg"
            class="img-fluid rounded-circle"
            alt="Azam"
          />
          <img
            src="images/Azam2.jpg"
            class="img-fluid rounded-circle"
            alt="Azam"
          />
          <img
            src="images/Azam3.jpg"
            class="img-fluid rounded-circle"
            alt="Azam"
          />
          <h2>Azam</h2>
          <p>
            Azam is the calm one of the group. She is also the only person who
            is an actual adult in this WG. She cooks amazing food! She is the
            biggest fan of Cinema and Movies in the WG, and will always save the
            night with a great suggestion of a series or a movie! Also, the
            person responsible for making sure this WG doesn't turn into a
            dumpster fire.
          </p>
        </div>
        <div class="col-md-4 mb-3">
          <img
            src="images/Dylan1.jpg"
            class="img-fluid rounded-circle"
            alt="Dylan"
          />
          <img
            src="images/Dylan2.jpg"
            class="img-fluid rounded-circle"
            alt="Dylan"
          />
          <img
            src="images/Dylan3.jpg"
            class="img-fluid rounded-circle"
            alt="Dylan"
          />
          <h2>Dylan</h2>
          <p>
            Dylan is the most competitive person in the WG. He likes every
            single sport to ever exist and has 2 moods: High Dylan or Drunk
            Dylan, both are fun to be around, but make sure you're on his same
            wavelength before you start a conversation with him.
          </p>
        </div>
        <div class="col-md-4 mb-3">
          <img
            src="images/Isa1.jpg"
            class="img-fluid rounded-circle"
            alt="Isa"
          />
          <img
            src="images/Isa2.jpg"
            class="img-fluid rounded-circle"
            alt="Isa"
          />
          <img
            src="images/Isa3.jpg"
            class="img-fluid rounded-circle"
            alt="Isa"
          />
          <h2>Isa</h2>
          <p>
            Isa is the wild card of the group. You never quite know what they
            are going to do next, but it's always guaranteed to be chaotic. They
            have a talent for coming up with most destructive ways of having
            fun.
            <small class="text-muted"
              >She doesn't even live here anymore but she lives in our hearts
              &#10084;</small
            >
          </p>
          <div class="col-md-4 mb-3">
            <img
              src="images/Nikhil1.jpg"
              class="img-fluid rounded-circle"
              alt="Nikhil"
            />
            <img
              src="images/Nikhil2.jpg"
              class="img-fluid rounded-circle"
              alt="Nikhil"
            />
            <img
              src="images/Nikhil3.jpg"
              class="img-fluid rounded-circle"
              alt="Nikhil"
            />

            <h2>Nikhil</h2>
            <p>
              The richest person of us all. Also the only one fully employed.
              Currently in India, so he's sadly not celebrating with us. We all
              miss Nikhil very very much :(.
              <small class="text-muted"
                >He also doesn't even live here anymore but he lives in our
                hearts &#10084;</small
              >
            </p>
          </div>
        </div>
      </div>