<!DOCTYPE html>
<html>
  <!-- rest of the code -->
  <body>
    <div class="container mt-5">
      <?php include 'partials/navbar.phtml'; ?>
      <h1 class="text-center mb-5">Registration Form</h1>
      <form onsubmit="event.preventDefault(); submitForm();">
        <!-- form content here -->
        <button type="submit" class="btn btn-primary btn-lg my-2 custom-button">
          Submit
        </button>
      </form>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
    <script src="registration.js"></script>
  </body>
</html>
